# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'b.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import detectron2
from detectron2.utils.logger import setup_logger
setup_logger()

# import some common libraries
import numpy as np
import os, json, cv2, random


# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer
from detectron2.data import MetadataCatalog, DatasetCatalog
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.cbook as cbook
from jieguo_window import *
from shibie_window import *
from xunlian_window import *
from tuxiang_window import *

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QFileDialog


class zhujiemian(QMainWindow):
    def __init__(self):
        super().__init__()
        MainWindow = self
        self.i = 1
        self.imgName = ""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1000)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 60, 700, 700))
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 800, 150, 46))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.to_shibie)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(900, 800, 150, 46))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.to_jieguo)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1200, 800, 150, 46))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.to_xunlian)

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 800, 150, 46))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.to_tuxiang)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setFont(QFont("宋体", 40, QFont.Bold))
        self.pushButton.setFont(QFont("宋体", 14, QFont.Bold))
        self.pushButton_2.setFont(QFont("宋体", 14, QFont.Bold))
        self.pushButton_3.setFont(QFont("宋体", 14, QFont.Bold))
        self.pushButton_4.setFont(QFont("宋体", 14, QFont.Bold))
        self.label.setText(_translate("MainWindow", "欢迎使用图像实例分割系统"))
        self.pushButton.setText(_translate("MainWindow", "图像识别"))
        self.pushButton_2.setText(_translate("MainWindow", "结果分析"))
        self.pushButton_3.setText(_translate("MainWindow", "模型训练"))
        self.pushButton_4.setText(_translate("MainWindow", "图像捕捉"))

    windowList = []

    def to_shibie(self):
        the_window = shibie_window()
        the_window.pushButton_4.clicked.connect(lambda: self.to_zhujiemian(the_window))
        self.windowList.append(the_window)  ##注：没有这句，是不打开另一个主界面的！
        self.close()
        the_window.show()


    def to_jieguo(self):
        the_window = jieguo_window()
        the_window.pushButton_3.clicked.connect(lambda: self.to_zhujiemian(the_window))
        self.windowList.append(the_window)  ##注：没有这句，是不打开另一个主界面的！
        self.close()
        the_window.show()

    def to_xunlian(self):
        the_window = xunlian_window()
        the_window.pushButton_3.clicked.connect(lambda: self.to_zhujiemian(the_window))
        self.windowList.append(the_window)  ##注：没有这句，是不打开另一个主界面的！
        self.close()
        the_window.show()

    def to_zhujiemian(self, the_window):
        self.show()
        the_window.close()

    def to_tuxiang(self):
        the_window = tuxiang_window()
        the_window.pushButton_4.clicked.connect(lambda: self.to_zhujiemian(the_window))
        self.windowList.append(the_window)  ##注：没有这句，是不打开另一个主界面的！
        self.close()
        the_window.show()